server:
  host: ${SERVER_HOST}
  port: 8080

spring:
  application:
    name: podo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  jackson:
    serialization:
      fail-on-empty-beans: false

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${BUCKET_ACCESS_KEY}
      secret-key: ${BUCKET_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

secret:
  jwt: ${SECRET_JWT}

message:
  sender: ${MESSAGE_SENDER}
  api-key: ${MESSAGE_KEY}
  api-secret-key: ${MESSAGE_SECRET_KEY}
  domain: ${MESSAGE_DOMAIN}
